/*
 * generated by Xtext 2.28.0
 */
package org.bpy.electronics.mc6809.assembler.ui;

import org.bpy.electronics.mc6809.assembler.ui.highlighting.AssemblerHighlightingConfiguration;
import org.bpy.electronics.mc6809.assembler.ui.highlighting.AssemblerSemanticHighLighting;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AssemblerUiModule extends AbstractAssemblerUiModule {

	/** Plugin identifier */
	public static final String PLUGIN_ID = "org.bpy.electronics.mc6809.assembler.ui";
	
	public AssemblerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	/**
	 * Bind the class which manage the high lighting configuration.
	 * 
	 * @return the class which manage the high lighting configuration.
	 */
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	     return AssemblerHighlightingConfiguration.class;
	}

	/**
	 * Bind the class which manage the semantic high lighting configuration.
	 * 
	 * @return the class which manage the semantic high lighting configuration.
	 */
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		 return AssemblerSemanticHighLighting.class;
	}

	public void configureFilterOperationsContribution(Binder binder) {
//		  binder.bind(IOutlineContribution.class).annotatedWith(
//			      Names.named("FilterOperationsContribution"))
//			    .to(FilterInstructionContribution.class);
//		  binder.bind(IOutlineContribution.class).annotatedWith(
//			      Names.named("FilterDirectiveContribution"))
//			    .to(FilterDirectiveContribution.class);
//		  binder.bind(IOutlineContribution.class).annotatedWith(
//			      Names.named("FilterMacroContribution"))
//			    .to(FilterMacroContribution.class);
//		  binder.bind(IOutlineContribution.class).annotatedWith(
//			      Names.named("FilterOtherContribution"))
//			    .to(FilterOtherContribution.class);
		}}
