/*
 * generated by Xtext 2.28.0
 */
package org.bpy.electronics.mc6809.assembler.ide;


/**
 * Use this class to register ide components.
 */
public class AssemblerIdeModule extends AbstractAssemblerIdeModule {
}
