package org.bpy.electronics.mc6809.rcp.builder;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.NullProgressMonitor;
import org.eclipse.jface.dialogs.MessageDialog;
import org.eclipse.swt.widgets.Display;
import org.eclipse.ui.IWorkbenchPage;
import org.eclipse.ui.PlatformUI;
import org.eclipse.ui.ide.IDE;

public class AssemblerFileBuilder {

	/** Logger of the class */
	private static final Logger logger = Logger.getLogger(AssemblerFileBuilder.class.getSimpleName());

	public static final StringBuilder TEMPLATE = new StringBuilder();

	/** Standard comment line */
	private static final String COMMENT_LINE = ";------------------------------------------------------------------\n";
	
	static {
		DateFormat df = new SimpleDateFormat("MMMM dd, yyyy");
		Date today = Calendar.getInstance().getTime();        
		String todayAsString = df.format(today);

		TEMPLATE.append(COMMENT_LINE);
		TEMPLATE.append("; Generated by the 6809 eclipse tool\n");
		TEMPLATE.append("; Genaration date : " + todayAsString + "\n");
		TEMPLATE.append(COMMENT_LINE);
		TEMPLATE.append("\n");
		TEMPLATE.append("\n");
		TEMPLATE.append(COMMENT_LINE);
	}

	/** 
	 * Create the optional assembly file.
	 * 
	 * @param project reference on the project
	 * @param optionalFileName name of the optional assembly file
	 */
	public void createAssemblyFile(IProject project, String optionalFileName) {
		IFile as9File = project.getFile(optionalFileName);
		try {
			
			InputStream targetStream = new ByteArrayInputStream(TEMPLATE.toString().getBytes());
			as9File.create(targetStream, false, new NullProgressMonitor());
			
			IWorkbenchPage page = PlatformUI.getWorkbench().getActiveWorkbenchWindow().getActivePage();
			IDE.openEditor(page, as9File);
		} catch (CoreException e) {
			MessageDialog.openError(Display.getCurrent().getActiveShell(), "File creation error", e.getMessage());
			logger.log(Level.SEVERE, e.getMessage());
		}
	}

}
