/**
 * generated by Xtext 2.28.0
 */
package org.bpy.electronics.mc6809.assembler.assembler.impl;

import java.util.Collection;

import org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage;
import org.bpy.electronics.mc6809.assembler.assembler.IdentifierValue;
import org.bpy.electronics.mc6809.assembler.assembler.InstructionLine;
import org.bpy.electronics.mc6809.assembler.assembler.MacroDefinition;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Macro Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.impl.MacroDefinitionImpl#getWs1 <em>Ws1</em>}</li>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.impl.MacroDefinitionImpl#getWs2 <em>Ws2</em>}</li>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.impl.MacroDefinitionImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.impl.MacroDefinitionImpl#getWs3 <em>Ws3</em>}</li>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.impl.MacroDefinitionImpl#getComment <em>Comment</em>}</li>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.impl.MacroDefinitionImpl#getWs4 <em>Ws4</em>}</li>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.impl.MacroDefinitionImpl#getInstructions <em>Instructions</em>}</li>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.impl.MacroDefinitionImpl#getWs5 <em>Ws5</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MacroDefinitionImpl extends MinimalEObjectImpl.Container implements MacroDefinition
{
  /**
   * The default value of the '{@link #getWs1() <em>Ws1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWs1()
   * @generated
   * @ordered
   */
  protected static final String WS1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWs1() <em>Ws1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWs1()
   * @generated
   * @ordered
   */
  protected String ws1 = WS1_EDEFAULT;

  /**
   * The default value of the '{@link #getWs2() <em>Ws2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWs2()
   * @generated
   * @ordered
   */
  protected static final String WS2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWs2() <em>Ws2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWs2()
   * @generated
   * @ordered
   */
  protected String ws2 = WS2_EDEFAULT;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected IdentifierValue name;

  /**
   * The default value of the '{@link #getWs3() <em>Ws3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWs3()
   * @generated
   * @ordered
   */
  protected static final String WS3_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWs3() <em>Ws3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWs3()
   * @generated
   * @ordered
   */
  protected String ws3 = WS3_EDEFAULT;

  /**
   * The default value of the '{@link #getComment() <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComment()
   * @generated
   * @ordered
   */
  protected static final String COMMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getComment() <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComment()
   * @generated
   * @ordered
   */
  protected String comment = COMMENT_EDEFAULT;

  /**
   * The default value of the '{@link #getWs4() <em>Ws4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWs4()
   * @generated
   * @ordered
   */
  protected static final String WS4_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWs4() <em>Ws4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWs4()
   * @generated
   * @ordered
   */
  protected String ws4 = WS4_EDEFAULT;

  /**
   * The cached value of the '{@link #getInstructions() <em>Instructions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstructions()
   * @generated
   * @ordered
   */
  protected EList<InstructionLine> instructions;

  /**
   * The default value of the '{@link #getWs5() <em>Ws5</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWs5()
   * @generated
   * @ordered
   */
  protected static final String WS5_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getWs5() <em>Ws5</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWs5()
   * @generated
   * @ordered
   */
  protected String ws5 = WS5_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MacroDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AssemblerPackage.Literals.MACRO_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getWs1()
  {
    return ws1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWs1(String newWs1)
  {
    String oldWs1 = ws1;
    ws1 = newWs1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AssemblerPackage.MACRO_DEFINITION__WS1, oldWs1, ws1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getWs2()
  {
    return ws2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWs2(String newWs2)
  {
    String oldWs2 = ws2;
    ws2 = newWs2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AssemblerPackage.MACRO_DEFINITION__WS2, oldWs2, ws2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IdentifierValue getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetName(IdentifierValue newName, NotificationChain msgs)
  {
    IdentifierValue oldName = name;
    name = newName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AssemblerPackage.MACRO_DEFINITION__NAME, oldName, newName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(IdentifierValue newName)
  {
    if (newName != name)
    {
      NotificationChain msgs = null;
      if (name != null)
        msgs = ((InternalEObject)name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AssemblerPackage.MACRO_DEFINITION__NAME, null, msgs);
      if (newName != null)
        msgs = ((InternalEObject)newName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AssemblerPackage.MACRO_DEFINITION__NAME, null, msgs);
      msgs = basicSetName(newName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AssemblerPackage.MACRO_DEFINITION__NAME, newName, newName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getWs3()
  {
    return ws3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWs3(String newWs3)
  {
    String oldWs3 = ws3;
    ws3 = newWs3;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AssemblerPackage.MACRO_DEFINITION__WS3, oldWs3, ws3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getComment()
  {
    return comment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setComment(String newComment)
  {
    String oldComment = comment;
    comment = newComment;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AssemblerPackage.MACRO_DEFINITION__COMMENT, oldComment, comment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getWs4()
  {
    return ws4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWs4(String newWs4)
  {
    String oldWs4 = ws4;
    ws4 = newWs4;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AssemblerPackage.MACRO_DEFINITION__WS4, oldWs4, ws4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InstructionLine> getInstructions()
  {
    if (instructions == null)
    {
      instructions = new EObjectContainmentEList<InstructionLine>(InstructionLine.class, this, AssemblerPackage.MACRO_DEFINITION__INSTRUCTIONS);
    }
    return instructions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getWs5()
  {
    return ws5;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWs5(String newWs5)
  {
    String oldWs5 = ws5;
    ws5 = newWs5;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AssemblerPackage.MACRO_DEFINITION__WS5, oldWs5, ws5));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AssemblerPackage.MACRO_DEFINITION__NAME:
        return basicSetName(null, msgs);
      case AssemblerPackage.MACRO_DEFINITION__INSTRUCTIONS:
        return ((InternalEList<?>)getInstructions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AssemblerPackage.MACRO_DEFINITION__WS1:
        return getWs1();
      case AssemblerPackage.MACRO_DEFINITION__WS2:
        return getWs2();
      case AssemblerPackage.MACRO_DEFINITION__NAME:
        return getName();
      case AssemblerPackage.MACRO_DEFINITION__WS3:
        return getWs3();
      case AssemblerPackage.MACRO_DEFINITION__COMMENT:
        return getComment();
      case AssemblerPackage.MACRO_DEFINITION__WS4:
        return getWs4();
      case AssemblerPackage.MACRO_DEFINITION__INSTRUCTIONS:
        return getInstructions();
      case AssemblerPackage.MACRO_DEFINITION__WS5:
        return getWs5();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AssemblerPackage.MACRO_DEFINITION__WS1:
        setWs1((String)newValue);
        return;
      case AssemblerPackage.MACRO_DEFINITION__WS2:
        setWs2((String)newValue);
        return;
      case AssemblerPackage.MACRO_DEFINITION__NAME:
        setName((IdentifierValue)newValue);
        return;
      case AssemblerPackage.MACRO_DEFINITION__WS3:
        setWs3((String)newValue);
        return;
      case AssemblerPackage.MACRO_DEFINITION__COMMENT:
        setComment((String)newValue);
        return;
      case AssemblerPackage.MACRO_DEFINITION__WS4:
        setWs4((String)newValue);
        return;
      case AssemblerPackage.MACRO_DEFINITION__INSTRUCTIONS:
        getInstructions().clear();
        getInstructions().addAll((Collection<? extends InstructionLine>)newValue);
        return;
      case AssemblerPackage.MACRO_DEFINITION__WS5:
        setWs5((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AssemblerPackage.MACRO_DEFINITION__WS1:
        setWs1(WS1_EDEFAULT);
        return;
      case AssemblerPackage.MACRO_DEFINITION__WS2:
        setWs2(WS2_EDEFAULT);
        return;
      case AssemblerPackage.MACRO_DEFINITION__NAME:
        setName((IdentifierValue)null);
        return;
      case AssemblerPackage.MACRO_DEFINITION__WS3:
        setWs3(WS3_EDEFAULT);
        return;
      case AssemblerPackage.MACRO_DEFINITION__COMMENT:
        setComment(COMMENT_EDEFAULT);
        return;
      case AssemblerPackage.MACRO_DEFINITION__WS4:
        setWs4(WS4_EDEFAULT);
        return;
      case AssemblerPackage.MACRO_DEFINITION__INSTRUCTIONS:
        getInstructions().clear();
        return;
      case AssemblerPackage.MACRO_DEFINITION__WS5:
        setWs5(WS5_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AssemblerPackage.MACRO_DEFINITION__WS1:
        return WS1_EDEFAULT == null ? ws1 != null : !WS1_EDEFAULT.equals(ws1);
      case AssemblerPackage.MACRO_DEFINITION__WS2:
        return WS2_EDEFAULT == null ? ws2 != null : !WS2_EDEFAULT.equals(ws2);
      case AssemblerPackage.MACRO_DEFINITION__NAME:
        return name != null;
      case AssemblerPackage.MACRO_DEFINITION__WS3:
        return WS3_EDEFAULT == null ? ws3 != null : !WS3_EDEFAULT.equals(ws3);
      case AssemblerPackage.MACRO_DEFINITION__COMMENT:
        return COMMENT_EDEFAULT == null ? comment != null : !COMMENT_EDEFAULT.equals(comment);
      case AssemblerPackage.MACRO_DEFINITION__WS4:
        return WS4_EDEFAULT == null ? ws4 != null : !WS4_EDEFAULT.equals(ws4);
      case AssemblerPackage.MACRO_DEFINITION__INSTRUCTIONS:
        return instructions != null && !instructions.isEmpty();
      case AssemblerPackage.MACRO_DEFINITION__WS5:
        return WS5_EDEFAULT == null ? ws5 != null : !WS5_EDEFAULT.equals(ws5);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ws1: ");
    result.append(ws1);
    result.append(", ws2: ");
    result.append(ws2);
    result.append(", ws3: ");
    result.append(ws3);
    result.append(", comment: ");
    result.append(comment);
    result.append(", ws4: ");
    result.append(ws4);
    result.append(", ws5: ");
    result.append(ws5);
    result.append(')');
    return result.toString();
  }

} //MacroDefinitionImpl
