/**
 * generated by Xtext 2.28.0
 */
package org.bpy.electronics.mc6809.assembler.assembler.impl;

import org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage;
import org.bpy.electronics.mc6809.assembler.assembler.SourceLine;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Source Line</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.impl.SourceLineImpl#getLineContent <em>Line Content</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SourceLineImpl extends MinimalEObjectImpl.Container implements SourceLine
{
  /**
   * The cached value of the '{@link #getLineContent() <em>Line Content</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLineContent()
   * @generated
   * @ordered
   */
  protected EObject lineContent;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SourceLineImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AssemblerPackage.Literals.SOURCE_LINE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject getLineContent()
  {
    return lineContent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLineContent(EObject newLineContent, NotificationChain msgs)
  {
    EObject oldLineContent = lineContent;
    lineContent = newLineContent;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AssemblerPackage.SOURCE_LINE__LINE_CONTENT, oldLineContent, newLineContent);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLineContent(EObject newLineContent)
  {
    if (newLineContent != lineContent)
    {
      NotificationChain msgs = null;
      if (lineContent != null)
        msgs = ((InternalEObject)lineContent).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AssemblerPackage.SOURCE_LINE__LINE_CONTENT, null, msgs);
      if (newLineContent != null)
        msgs = ((InternalEObject)newLineContent).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AssemblerPackage.SOURCE_LINE__LINE_CONTENT, null, msgs);
      msgs = basicSetLineContent(newLineContent, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AssemblerPackage.SOURCE_LINE__LINE_CONTENT, newLineContent, newLineContent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AssemblerPackage.SOURCE_LINE__LINE_CONTENT:
        return basicSetLineContent(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AssemblerPackage.SOURCE_LINE__LINE_CONTENT:
        return getLineContent();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AssemblerPackage.SOURCE_LINE__LINE_CONTENT:
        setLineContent((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AssemblerPackage.SOURCE_LINE__LINE_CONTENT:
        setLineContent((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AssemblerPackage.SOURCE_LINE__LINE_CONTENT:
        return lineContent != null;
    }
    return super.eIsSet(featureID);
  }

} //SourceLineImpl
