/*
 * generated by Xtext 2.28.0
 */
package org.bpy.electronics.mc6809.assembler.formatting2;

import org.bpy.electronics.mc6809.assembler.assembler.AbxInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.AdcInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.AddInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.AdddInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.AndCCInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.AndInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.AslInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.AsrInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage;
import org.bpy.electronics.mc6809.assembler.assembler.BccInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BcsInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BeqInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BgeInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BgtInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BhiInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BhsInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BitInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BleInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BloInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BlsInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BltInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BmiInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BneInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BplInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BraInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BrnInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BsrInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BszDirective;
import org.bpy.electronics.mc6809.assembler.assembler.BvcInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.BvsInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.ClrInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.CmpInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.ComInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.CommentLine;
import org.bpy.electronics.mc6809.assembler.assembler.CwaiInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.DaaInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.DecInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.DirectiveLine;
import org.bpy.electronics.mc6809.assembler.assembler.EndDirective;
import org.bpy.electronics.mc6809.assembler.assembler.EorInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.EquDirective;
import org.bpy.electronics.mc6809.assembler.assembler.ExgInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.FailDirective;
import org.bpy.electronics.mc6809.assembler.assembler.FcbDirective;
import org.bpy.electronics.mc6809.assembler.assembler.FccDirective;
import org.bpy.electronics.mc6809.assembler.assembler.FdbDirective;
import org.bpy.electronics.mc6809.assembler.assembler.FillDirective;
import org.bpy.electronics.mc6809.assembler.assembler.IncInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.InstructionLine;
import org.bpy.electronics.mc6809.assembler.assembler.JmpInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.JsrInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.Label;
import org.bpy.electronics.mc6809.assembler.assembler.LabelLine;
import org.bpy.electronics.mc6809.assembler.assembler.LdInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.LeaInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.LslInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.LsrInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.Model;
import org.bpy.electronics.mc6809.assembler.assembler.MulInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.NamDirective;
import org.bpy.electronics.mc6809.assembler.assembler.NegInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.NopInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.OptDirective;
import org.bpy.electronics.mc6809.assembler.assembler.OrInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.OrgDirective;
import org.bpy.electronics.mc6809.assembler.assembler.PagDirective;
import org.bpy.electronics.mc6809.assembler.assembler.PshsInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.PshuInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.PulsInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.PuluInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.RegDirective;
import org.bpy.electronics.mc6809.assembler.assembler.RmbDirective;
import org.bpy.electronics.mc6809.assembler.assembler.RolInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.RorInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.RtiInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.RtsInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.SbcInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.SetDPDirective;
import org.bpy.electronics.mc6809.assembler.assembler.SetDirective;
import org.bpy.electronics.mc6809.assembler.assembler.SexInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.SourceLine;
import org.bpy.electronics.mc6809.assembler.assembler.SpcDirective;
import org.bpy.electronics.mc6809.assembler.assembler.StInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.SubInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.SubdInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.Swi2Instruction;
import org.bpy.electronics.mc6809.assembler.assembler.Swi3Instruction;
import org.bpy.electronics.mc6809.assembler.assembler.SwiInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.SyncInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.TfrInstruction;
import org.bpy.electronics.mc6809.assembler.assembler.TstInstruction;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.BszFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.EndFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.EquFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.FailFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.FcbFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.FccFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.FdbFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.FillFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.NamFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.OptFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.OrgFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.PagFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.RegFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.RmbFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.SetDPFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.SetFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.directives.SpcFormatter;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.AbxInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.AdcInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.AddInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.AdddInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.AndCCInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.AndInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.AslInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.AsrInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BccInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BcsInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BeqInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BgeInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BgtInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BhiInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BhsInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BitInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BleInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BloInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BlsInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BltInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BmiInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BneInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BplInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BraInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BrnInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BsrInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BvcInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.BvsInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.ClrInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.CmpInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.ComInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.CwaiInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.DaaInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.DecInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.EorInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.ExgInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.IncInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.JmpInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.JsrInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.LdInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.LeaInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.LslInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.LsrInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.MulInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.NegInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.NopInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.OrInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.PshsInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.PshuInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.PulsInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.PuluInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.RolInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.RorInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.RtiInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.RtsInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.SbcInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.SexInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.StInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.SubInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.SubdInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.Swi2InstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.Swi3InstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.SwiInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.SyncInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.TfrInstructionFormater;
import org.bpy.electronics.mc6809.assembler.formatting2.instructions.TstInstructionFormater;
import org.bpy.electronics.mc6809.preferences.core.PreferenceManager;
import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatting;
import org.eclipse.xtext.formatting2.ITextReplacer;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion;
import org.eclipse.xtext.formatting2.regionaccess.ITextRegionExtensions;
import org.eclipse.xtext.xbase.lib.ObjectExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

import com.google.common.base.Strings;

/**
 * Formatter.
 * 
 * @author Patrick BRIAND
 *
 */
public class AssemblerFormatter extends AbstractJavaFormatter {

	/** Reference on the preference manager */
	private PreferenceManager preferenceManager;

	/** Current value of the tab policy */
	private String tabPolicy;

	/** Current value of the tab size */
	private int tabSize;

	/** Current column value of the instruction */
	private int instructionPosition;

	/** Current column value of the operand */
	private int operandPosition;

	/** Current column value of the comment */
	private int commentPosition;

	/** Just use for a workaround on JUnit test of the formatter */
	private boolean junitPreference;

	/**
	 * Entry for format all document.
	 * 
	 * @param model reference on the model
	 * @param doc   reference on the document
	 */
	protected void format(Model model, IFormattableDocument doc) {
		preferenceManager = PreferenceManager.getInstance();
		junitPreference = this.preferenceManager.getBooleanPreferenceValue(PreferenceManager.JUNIT_PREFERENCE);
		tabPolicy = this.preferenceManager.getStringPreferenceValue(PreferenceManager.TAB_POLICY);
		tabSize = this.preferenceManager.getIntPreferenceValue(PreferenceManager.TAB_SIZE);
		instructionPosition = this.preferenceManager.getIntPreferenceValue(PreferenceManager.INSTRUCTION_POSITION);
		operandPosition = this.preferenceManager.getIntPreferenceValue(PreferenceManager.OPERAND_POSITION);
		commentPosition = this.preferenceManager.getIntPreferenceValue(PreferenceManager.COMMENT_POSITION);

		System.out.println("--------------------------------------------------------------");
		System.out.println("Use formatter with following paramaters: ");
		System.out.print("Tab policy = " + tabPolicy);
		System.out.print(": Tab size = " + tabSize);
		System.out.print(": Instruction position = " + instructionPosition);
		System.out.print(": Operand position " + operandPosition);
		System.out.println(": Comment position " + commentPosition);

		for (SourceLine sourceLine : model.getSourceLines()) {
			doc.format(sourceLine);
		}
	}

	/**
	 * Format a source line.
	 * 
	 * @param sourceLine reference to a source line
	 * @param doc        reference to the document
	 */
	protected void format(SourceLine sourceLine, IFormattableDocument doc) {
		if (sourceLine.getLineContent() instanceof CommentLine commentLine) {
			doc.format(commentLine);

		} else if (sourceLine.getLineContent() instanceof LabelLine labelLine) {
			doc.format(labelLine);

		} else if (sourceLine.getLineContent() instanceof DirectiveLine directiveLine) {
			doc.format(directiveLine);

		} else if (sourceLine.getLineContent() instanceof InstructionLine instructionLine) {
			doc.format(instructionLine);
		}
	}

	/**
	 * Format all instructions element.
	 * 
	 * @param line reference on the instruction line
	 * @param doc reference on the document
	 */
	protected void format(InstructionLine line, IFormattableDocument doc) {
		setFirstWhiteSpace(doc, line, getLabelSize(line.getLabel()), AssemblerPackage.eINSTANCE.getInstructionLine_Ws1());

		if (line.getInstruction() instanceof AbxInstruction abxInstruction) {
			AbxInstructionFormater abxFormatter = new AbxInstructionFormater(doc, tabPolicy, tabSize);
			abxFormatter.format(this, abxInstruction, instructionPosition, operandPosition);
		
		} else if (line.getInstruction() instanceof AdcInstruction adcInstruction) {
			AdcInstructionFormater adcFormatter = new AdcInstructionFormater(doc, tabPolicy, tabSize);
			adcFormatter.format(this, adcInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof AddInstruction addInstruction) {
			AddInstructionFormater adcFormatter = new AddInstructionFormater(doc, tabPolicy, tabSize);
			adcFormatter.format(this, addInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof AdddInstruction adddInstruction) {
			AdddInstructionFormater adddFormatter = new AdddInstructionFormater(doc, tabPolicy, tabSize);
			adddFormatter.format(this, adddInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof AndInstruction andInstruction) {
			AndInstructionFormater andFormatter = new AndInstructionFormater(doc, tabPolicy, tabSize);
			andFormatter.format(this, andInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof AndCCInstruction andccInstruction) {
			AndCCInstructionFormater andccFormatter = new AndCCInstructionFormater(doc, tabPolicy, tabSize);
			andccFormatter.format(this, andccInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof AslInstruction aslInstruction) {
			AslInstructionFormater aslFormatter = new AslInstructionFormater(doc, tabPolicy, tabSize);
			aslFormatter.format(this, aslInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof AsrInstruction asrInstruction) {
			AsrInstructionFormater asrFormatter = new AsrInstructionFormater(doc, tabPolicy, tabSize);
			asrFormatter.format(this, asrInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BitInstruction bitInstruction) {
			BitInstructionFormater bitFormatter = new BitInstructionFormater(doc, tabPolicy, tabSize);
			bitFormatter.format(this, bitInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof ClrInstruction clrInstruction) {
			ClrInstructionFormater clrFormatter = new ClrInstructionFormater(doc, tabPolicy, tabSize);
			clrFormatter.format(this, clrInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof CmpInstruction cmpInstruction) {
			CmpInstructionFormater cmpFormatter = new CmpInstructionFormater(doc, tabPolicy, tabSize);
			cmpFormatter.format(this, cmpInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof ComInstruction comInstruction) {
			ComInstructionFormater comFormatter = new ComInstructionFormater(doc, tabPolicy, tabSize);
			comFormatter.format(this, comInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof CwaiInstruction cwaiInstruction) {
			CwaiInstructionFormater cwaiFormatter = new CwaiInstructionFormater(doc, tabPolicy, tabSize);
			cwaiFormatter.format(this, cwaiInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof DaaInstruction daaInstruction) {
			DaaInstructionFormater daaFormatter = new DaaInstructionFormater(doc, tabPolicy, tabSize);
			daaFormatter.format(this, daaInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof DecInstruction decInstruction) {
			DecInstructionFormater decFormatter = new DecInstructionFormater(doc, tabPolicy, tabSize);
			decFormatter.format(this, decInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof ExgInstruction exgInstruction) {
			ExgInstructionFormater exgFormatter = new ExgInstructionFormater(doc, tabPolicy, tabSize);
			exgFormatter.format(this, exgInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof IncInstruction incInstruction) {
			IncInstructionFormater incFormatter = new IncInstructionFormater(doc, tabPolicy, tabSize);
			incFormatter.format(this, incInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof JmpInstruction jmpInstruction) {
			JmpInstructionFormater jmpFormatter = new JmpInstructionFormater(doc, tabPolicy, tabSize);
			jmpFormatter.format(this, jmpInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof JsrInstruction jsrInstruction) {
			JsrInstructionFormater jsrFormatter = new JsrInstructionFormater(doc, tabPolicy, tabSize);
			jsrFormatter.format(this, jsrInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof LdInstruction ldInstruction) {
			LdInstructionFormater ldFormatter = new LdInstructionFormater(doc, tabPolicy, tabSize);
			ldFormatter.format(this, ldInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof LeaInstruction leaInstruction) {
			LeaInstructionFormater leaFormatter = new LeaInstructionFormater(doc, tabPolicy, tabSize);
			leaFormatter.format(this, leaInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof LslInstruction lslInstruction) {
			LslInstructionFormater lslFormatter = new LslInstructionFormater(doc, tabPolicy, tabSize);
			lslFormatter.format(this, lslInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof LsrInstruction lsrInstruction) {
			LsrInstructionFormater lsrFormatter = new LsrInstructionFormater(doc, tabPolicy, tabSize);
			lsrFormatter.format(this, lsrInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof MulInstruction mulInstruction) {
			MulInstructionFormater mulFormatter = new MulInstructionFormater(doc, tabPolicy, tabSize);
			mulFormatter.format(this, mulInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof NegInstruction negInstruction) {
			NegInstructionFormater negFormatter = new NegInstructionFormater(doc, tabPolicy, tabSize);
			negFormatter.format(this, negInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof NopInstruction nopInstruction) {
			NopInstructionFormater nopFormatter = new NopInstructionFormater(doc, tabPolicy, tabSize);
			nopFormatter.format(this, nopInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof OrInstruction orInstruction) {
			OrInstructionFormater orFormatter = new OrInstructionFormater(doc, tabPolicy, tabSize);
			orFormatter.format(this, orInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof PshsInstruction pshsInstruction) {
			PshsInstructionFormater pshsFormatter = new PshsInstructionFormater(doc, tabPolicy, tabSize);
			pshsFormatter.format(this, pshsInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof PshuInstruction pshuInstruction) {
			PshuInstructionFormater pshuFormatter = new PshuInstructionFormater(doc, tabPolicy, tabSize);
			pshuFormatter.format(this, pshuInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof PulsInstruction pulsInstruction) {
			PulsInstructionFormater pulsFormatter = new PulsInstructionFormater(doc, tabPolicy, tabSize);
			pulsFormatter.format(this, pulsInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof PuluInstruction puluInstruction) {
			PuluInstructionFormater puluFormatter = new PuluInstructionFormater(doc, tabPolicy, tabSize);
			puluFormatter.format(this, puluInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof RolInstruction rolInstruction) {
			RolInstructionFormater rolFormatter = new RolInstructionFormater(doc, tabPolicy, tabSize);
			rolFormatter.format(this, rolInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof RorInstruction rorInstruction) {
			RorInstructionFormater rorFormatter = new RorInstructionFormater(doc, tabPolicy, tabSize);
			rorFormatter.format(this, rorInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof RtiInstruction rtiInstruction) {
			RtiInstructionFormater rtiFormatter = new RtiInstructionFormater(doc, tabPolicy, tabSize);
			rtiFormatter.format(this, rtiInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof RtsInstruction rtsInstruction) {
			RtsInstructionFormater rtsFormatter = new RtsInstructionFormater(doc, tabPolicy, tabSize);
			rtsFormatter.format(this, rtsInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof SbcInstruction sbcInstruction) {
			SbcInstructionFormater sbcFormatter = new SbcInstructionFormater(doc, tabPolicy, tabSize);
			sbcFormatter.format(this, sbcInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof SexInstruction sexInstruction) {
			SexInstructionFormater sexFormatter = new SexInstructionFormater(doc, tabPolicy, tabSize);
			sexFormatter.format(this, sexInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof StInstruction stInstruction) {
			StInstructionFormater stFormatter = new StInstructionFormater(doc, tabPolicy, tabSize);
			stFormatter.format(this, stInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof SubInstruction subInstruction) {
			SubInstructionFormater subFormatter = new SubInstructionFormater(doc, tabPolicy, tabSize);
			subFormatter.format(this, subInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof SubdInstruction subdInstruction) {
			SubdInstructionFormater subdFormatter = new SubdInstructionFormater(doc, tabPolicy, tabSize);
			subdFormatter.format(this, subdInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof SwiInstruction swiInstruction) {
			SwiInstructionFormater swiFormatter = new SwiInstructionFormater(doc, tabPolicy, tabSize);
			swiFormatter.format(this, swiInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof Swi2Instruction swi2Instruction) {
			Swi2InstructionFormater swi2Formatter = new Swi2InstructionFormater(doc, tabPolicy, tabSize);
			swi2Formatter.format(this, swi2Instruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof Swi3Instruction swi3Instruction) {
			Swi3InstructionFormater swi3Formatter = new Swi3InstructionFormater(doc, tabPolicy, tabSize);
			swi3Formatter.format(this, swi3Instruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof SyncInstruction syncInstruction) {
			SyncInstructionFormater syncFormatter = new SyncInstructionFormater(doc, tabPolicy, tabSize);
			syncFormatter.format(this, syncInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof TfrInstruction tfrInstruction) {
			TfrInstructionFormater tfrFormatter = new TfrInstructionFormater(doc, tabPolicy, tabSize);
			tfrFormatter.format(this, tfrInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof TstInstruction tstInstruction) {
			TstInstructionFormater tstFormatter = new TstInstructionFormater(doc, tabPolicy, tabSize);
			tstFormatter.format(this, tstInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BccInstruction bccInstruction) {
			BccInstructionFormater bccFormatter = new BccInstructionFormater(doc, tabPolicy, tabSize);
			bccFormatter.format(this, bccInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BcsInstruction bcsInstruction) {
			BcsInstructionFormater bcsFormatter = new BcsInstructionFormater(doc, tabPolicy, tabSize);
			bcsFormatter.format(this, bcsInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BeqInstruction beqInstruction) {
			BeqInstructionFormater beqFormatter = new BeqInstructionFormater(doc, tabPolicy, tabSize);
			beqFormatter.format(this, beqInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BgeInstruction bgeInstruction) {
			BgeInstructionFormater bgeFormatter = new BgeInstructionFormater(doc, tabPolicy, tabSize);
			bgeFormatter.format(this, bgeInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BgtInstruction bgtInstruction) {
			BgtInstructionFormater bgtFormatter = new BgtInstructionFormater(doc, tabPolicy, tabSize);
			bgtFormatter.format(this, bgtInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BhiInstruction bhiInstruction) {
			BhiInstructionFormater bhiFormatter = new BhiInstructionFormater(doc, tabPolicy, tabSize);
			bhiFormatter.format(this, bhiInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BhsInstruction bhsInstruction) {
			BhsInstructionFormater bhsFormatter = new BhsInstructionFormater(doc, tabPolicy, tabSize);
			bhsFormatter.format(this, bhsInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BleInstruction bleInstruction) {
			BleInstructionFormater bleFormatter = new BleInstructionFormater(doc, tabPolicy, tabSize);
			bleFormatter.format(this, bleInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BloInstruction bloInstruction) {
			BloInstructionFormater bloFormatter = new BloInstructionFormater(doc, tabPolicy, tabSize);
			bloFormatter.format(this, bloInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BlsInstruction blsInstruction) {
			BlsInstructionFormater blsFormatter = new BlsInstructionFormater(doc, tabPolicy, tabSize);
			blsFormatter.format(this, blsInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BltInstruction bltInstruction) {
			BltInstructionFormater bltFormatter = new BltInstructionFormater(doc, tabPolicy, tabSize);
			bltFormatter.format(this, bltInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BmiInstruction bmiInstruction) {
			BmiInstructionFormater bmiFormatter = new BmiInstructionFormater(doc, tabPolicy, tabSize);
			bmiFormatter.format(this, bmiInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BneInstruction bneInstruction) {
			BneInstructionFormater bneFormatter = new BneInstructionFormater(doc, tabPolicy, tabSize);
			bneFormatter.format(this, bneInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BplInstruction bplInstruction) {
			BplInstructionFormater bplFormatter = new BplInstructionFormater(doc, tabPolicy, tabSize);
			bplFormatter.format(this, bplInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BraInstruction braInstruction) {
			BraInstructionFormater braFormatter = new BraInstructionFormater(doc, tabPolicy, tabSize);
			braFormatter.format(this, braInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BrnInstruction brnInstruction) {
			BrnInstructionFormater brnFormatter = new BrnInstructionFormater(doc, tabPolicy, tabSize);
			brnFormatter.format(this, brnInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BsrInstruction bsrInstruction) {
			BsrInstructionFormater bsrFormatter = new BsrInstructionFormater(doc, tabPolicy, tabSize);
			bsrFormatter.format(this, bsrInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BvcInstruction bvcInstruction) {
			BvcInstructionFormater bvcFormatter = new BvcInstructionFormater(doc, tabPolicy, tabSize);
			bvcFormatter.format(this, bvcInstruction, instructionPosition, operandPosition);

		} else if (line.getInstruction() instanceof BvsInstruction bvsInstruction) {
			BvsInstructionFormater bvsFormatter = new BvsInstructionFormater(doc, tabPolicy, tabSize);
			bvsFormatter.format(this, bvsInstruction, instructionPosition, operandPosition);

		}

		if (line.getWs2() != null) {
			formatCommentPosition(doc, line, AssemblerPackage.eINSTANCE.getInstructionLine_Ws1(), AssemblerPackage.eINSTANCE.getInstructionLine_Ws2());
		}
	}

	/**
	 * Format a directive line. 
	 * 
	 * @param line reference on the directive line
	 * @param doc  reference on the current document
	 */
	protected void formatDirective(DirectiveLine line, IFormattableDocument doc) {
		
		setFirstWhiteSpace(doc, line, getLabelSize(line.getLabel()), AssemblerPackage.eINSTANCE.getDirectiveLine_Ws1());

		if (line.getDirective() instanceof BszDirective bszDirective) {
			BszFormatter bszFormatter = new BszFormatter(doc, tabPolicy, tabSize);
			bszFormatter.format(this, bszDirective, instructionPosition, operandPosition);

		} else if (line.getDirective() instanceof EndDirective endDirective) {
			EndFormatter endFormatter = new EndFormatter(doc, tabPolicy, tabSize);
			endFormatter.format(this, endDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof EquDirective equDirective) {
			EquFormatter equFormatter = new EquFormatter(doc, tabPolicy, tabSize);
			equFormatter.format(this, equDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof FailDirective failDirective) {
			FailFormatter failFormatter = new FailFormatter(doc, tabPolicy, tabSize);
			failFormatter.format(this, failDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof FcbDirective fcbDirective) {
			FcbFormatter fcbFormatter = new FcbFormatter(doc, tabPolicy, tabSize);
			fcbFormatter.format(this, fcbDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof FccDirective fccDirective) {
			FccFormatter fccFormatter = new FccFormatter(doc, tabPolicy, tabSize);
			fccFormatter.format(this, fccDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof FdbDirective fdbDirective) {
			FdbFormatter fdbFormatter = new FdbFormatter(doc, tabPolicy, tabSize);
			fdbFormatter.format(this, fdbDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof FillDirective fillDirective) {
			FillFormatter fillFormatter = new FillFormatter(doc, tabPolicy, tabSize);
			fillFormatter.format(this, fillDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof NamDirective namDirective) {
			NamFormatter namFormatter = new NamFormatter(doc, tabPolicy, tabSize);
			namFormatter.format(this, namDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof OptDirective optDirective) {
			OptFormatter optFormatter = new OptFormatter(doc, tabPolicy, tabSize);
			optFormatter.format(this, optDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof OrgDirective orgDirective) {
			OrgFormatter orgFormatter = new OrgFormatter(doc, tabPolicy, tabSize);
			orgFormatter.format(this, orgDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof PagDirective pagDirective) {
			PagFormatter pagFormatter = new PagFormatter(doc, tabPolicy, tabSize);
			pagFormatter.format(this, pagDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof RegDirective regDirective) {
			RegFormatter regFormatter = new RegFormatter(doc, tabPolicy, tabSize);
			regFormatter.format(this, regDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof RmbDirective rmbDirective) {
			RmbFormatter rmbFormatter = new RmbFormatter(doc, tabPolicy, tabSize);
			rmbFormatter.format(this, rmbDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof SetDirective setDirective) {
			SetFormatter setFormatter = new SetFormatter(doc, tabPolicy, tabSize);
			setFormatter.format(this, setDirective, instructionPosition, operandPosition);
		
		} else if (line.getDirective() instanceof SetDPDirective setdpDirective) {
			SetDPFormatter setdpFormatter = new SetDPFormatter(doc, tabPolicy, tabSize);
			setdpFormatter.format(this, setdpDirective, instructionPosition, operandPosition);

		} else if (line.getDirective() instanceof SpcDirective spcDirective) {
			SpcFormatter spcFormatter = new SpcFormatter(doc, tabPolicy, tabSize);
			spcFormatter.format(this, spcDirective, instructionPosition, operandPosition);
		
		}

		if (line.getWs2() != null) {
			formatCommentPosition(doc, line, AssemblerPackage.eINSTANCE.getDirectiveLine_Ws1(), AssemblerPackage.eINSTANCE.getDirectiveLine_Ws2());
		}
	}

	/** 
	 * Format a line of type label.
	 * 
	 * @param labelLine reference on the line
	 * @param doc reference on the document
	 */
	protected void format(LabelLine labelLine, IFormattableDocument doc) {
		setWhiteSpace(doc, labelLine,  AssemblerPackage.eINSTANCE.getLabelLine_Ws1(), " ");

		int nbSpacesNeeded = commentPosition - labelLine.getLabel().getName().getValue().length();
		String spaces = buildSpaceStringFromPolicy(labelLine.getLabel().getName().getValue().length(), 
				nbSpacesNeeded-1, 0);

		Procedure1<IHiddenRegionFormatter> spacesFunction = it -> it.setSpace(spaces);
		doc.append(this.textRegionExtensions.regionFor(labelLine).feature(AssemblerPackage.eINSTANCE.getLabelLine_Ws1()), spacesFunction);
	}

	/**
	 * Call the formatter for a line which start with space and contains only a
	 * comment.
	 * 
	 * @param commentLine reference on the comment line
	 * @param doc         reference on the document
	 */
	protected void format(CommentLine commentLine, IFormattableDocument doc) {
		setWhiteSpace(doc, commentLine,  AssemblerPackage.eINSTANCE.getCommentLine_StartingSpace(), " ");

		String spaces = buildSpaceStringFromPolicy(0, commentPosition-1, 0);

		Procedure1<IHiddenRegionFormatter> spacesFunction = it -> it.setSpace(spaces);
		doc.append(this.textRegionExtensions.regionFor(commentLine).feature(AssemblerPackage.eINSTANCE.getCommentLine_StartingSpace()), spacesFunction);
	}


	/**
	 * Format the comment between the operand and the comment, or between the keyword and
	 * and the comment if the operand doesn't exist.
	 * 
	 * @param doc reference on the document
	 * @param assemblyLine reference on the directive or instruction line
	 * @param ws1 EAttribute which define the first space element
	 * @param ws2 EAttribute which define the second space element
	 * @param comment EAttribute which define the comment element
	 */
	private void formatCommentPosition(IFormattableDocument doc, EObject assemblyLine, EAttribute ws1, EAttribute ws2) {
		try {
			ISemanticRegion lastNodeInstruction = textRegionExtensions.regionFor(assemblyLine).feature(ws2).getPreviousSemanticRegion();
			ISemanticRegion firstNodeInstruction = this.textRegionExtensions.regionFor(assemblyLine).feature(ws1).getNextSemanticRegion();

			int nbSpaces = 0;

			int elementReferenceSize;
			int startPosition = 0;
			
			if (firstNodeInstruction == lastNodeInstruction) {
				elementReferenceSize = firstNodeInstruction.getText().trim().length();
				nbSpaces = commentPosition - elementReferenceSize - (instructionPosition);
				startPosition = instructionPosition;
			} else {
				elementReferenceSize = getOperandSize(lastNodeInstruction);
				nbSpaces = commentPosition - elementReferenceSize - (operandPosition);
				startPosition = operandPosition;
			}

			String spacesAfterInstruction = buildSpaceStringFromPolicy(elementReferenceSize,nbSpaces, startPosition);
			setWhiteSpace(doc, assemblyLine, ws2, spacesAfterInstruction);
		} catch (Exception e) {
			// just for avoid unexpected messages 	
		}
	}

	/**
	 * Common function for set the space between the label and the instruction.
	 * 
	 * @param doc reference on the document
	 * @param line reference on the directive or instruction line
	 * @param labelSize size of the label
	 * @param ws EAttribute which define the space element
	 */
	private void setFirstWhiteSpace(IFormattableDocument doc, EObject line, int labelSize, EAttribute ws) { 
		String spaceBeforeKeyword = buildSpaceStringFromPolicy(labelSize, instructionPosition - labelSize -1, 0);
		if (labelSize ==0) {
			setWhiteSpace(doc, line, ws, " ");

			Procedure1<IHiddenRegionFormatter> spacesFunction = it -> it.setSpace(spaceBeforeKeyword);
			doc.append(this.textRegionExtensions.regionFor(line).feature(ws), spacesFunction);

		} else if (ws != null) {
			setWhiteSpace(doc, line, ws, spaceBeforeKeyword);
		}
	}

	/**
	 * Create a string in function of the tab policy.
	 * 
	 * @param elementSize Size of the label
	 * @param nbSpacesNeeded number of space needed
	 * @param startPosition position of the first char of the element before the spaces 
	 * @return string for create space
	 */
	public String buildSpaceStringFromPolicy(int elementSize, int nbSpacesNeeded, int startPosition) {

		if (PreferenceManager.SPACE_ONLY.equals(tabPolicy) ) {
			return Strings.repeat(" ", nbSpacesNeeded);
		
		} else if (PreferenceManager.TAB_ONLY.equals(tabPolicy)) {
			int nbTabsNeeded = ((elementSize%tabSize)==0) ? nbSpacesNeeded/tabSize : nbSpacesNeeded/tabSize + 1;
			if (nbTabsNeeded<1) {
				nbTabsNeeded =1;
			}
			return Strings.repeat("\t", nbTabsNeeded);
		
		} else {

			StringBuilder strBuilder = new StringBuilder();
			if (nbSpacesNeeded < tabSize) {
				strBuilder.append(Strings.repeat(" ", nbSpacesNeeded));
				return strBuilder.toString();

			} else {
				int missingSpaces = 0;
				if (startPosition == 0) {
					missingSpaces = (startPosition+elementSize)%tabSize;
				} else {
					missingSpaces = (startPosition+elementSize-1)%tabSize;
				}
				strBuilder.append("\t");
				nbSpacesNeeded -= (tabSize - missingSpaces);

				strBuilder.append(Strings.repeat("\t", nbSpacesNeeded/tabSize));
				strBuilder.append(Strings.repeat(" ", nbSpacesNeeded%tabSize));
				
				return strBuilder.toString();
			}
		}
	}

	/** 
	 * Return the number of byte of the operand.
	 * 
	 * @param start reference on the first element of the operand
	 * @return Size of the operand
	 */
	private int getOperandSize(ISemanticRegion start) {
		int length = 0;
		ISemanticRegion currentNode = start;
		boolean end = false;
		while (!end) {
			length += currentNode.getText().length();
			currentNode = currentNode.getPreviousSemanticRegion();
			end = currentNode.getText().isBlank();
		}
		return length;
	}

	/**
	 * Compute the size of a label
	 * 
	 * @param label reference on the label
	 * @return number of chars in the label
	 */
	private int getLabelSize(Label label) {
		if (label.getName() != null) {
			int size = label.getName().getValue().length();
			if (label.isPoint()) {
				size++;
			}
			return size;
		}
		return 0;
	}

	/**
	 * Remove a white space.
	 * 
	 * @param document        reference on the document
	 * @param line            reference on the instruction or directive line
	 * @param elementAttribut reference on the white space to remove
	 */
	private void setWhiteSpace(IFormattableDocument document, EObject line, EAttribute elementAttribut, String spaces) {
		IHiddenRegionFormatting hiddenRegion = document.getFormatter().createHiddenRegionFormatting();
		Procedure1<IHiddenRegionFormatting> spacesFunction = it -> it.setSpace(spaces);

		IHiddenRegionFormatting fmt = ObjectExtensions.<IHiddenRegionFormatting>operator_doubleArrow(hiddenRegion, spacesFunction);
		ITextReplacer replacer = createWhitespaceReplacer(textRegionExtensions.regionFor(line).feature(elementAttribut), fmt);
		try {
			document.addReplacer(replacer);
		} catch (Exception ex) {
//			Just for avoid unexpected messages
		}
	}

	public ITextRegionExtensions getTextRegionFormatter() {
		return textRegionExtensions;
	}

}
