/**
 * generated by Xtext 2.28.0
 */
package org.bpy.electronics.mc6809.assembler.assembler;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ascii Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.AsciiValue#getAsciiValue <em>Ascii Value</em>}</li>
 * </ul>
 *
 * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getAsciiValue()
 * @model
 * @generated
 */
public interface AsciiValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Ascii Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ascii Value</em>' attribute.
   * @see #setAsciiValue(String)
   * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getAsciiValue_AsciiValue()
   * @model
   * @generated
   */
  String getAsciiValue();

  /**
   * Sets the value of the '{@link org.bpy.electronics.mc6809.assembler.assembler.AsciiValue#getAsciiValue <em>Ascii Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ascii Value</em>' attribute.
   * @see #getAsciiValue()
   * @generated
   */
  void setAsciiValue(String value);

} // AsciiValue
