/**
 * generated by Xtext 2.29.0
 */
package org.bpy.electronics.mc6809.assembler.assembler;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Auto Inc Dec Mode</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.AutoIncDecMode#getDeplacement <em>Deplacement</em>}</li>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.AutoIncDecMode#getDecrement <em>Decrement</em>}</li>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.AutoIncDecMode#getRegister <em>Register</em>}</li>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.AutoIncDecMode#getIncrement <em>Increment</em>}</li>
 * </ul>
 *
 * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getAutoIncDecMode()
 * @model
 * @generated
 */
public interface AutoIncDecMode extends EObject
{
  /**
   * Returns the value of the '<em><b>Deplacement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deplacement</em>' containment reference.
   * @see #setDeplacement(NumericalValue)
   * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getAutoIncDecMode_Deplacement()
   * @model containment="true"
   * @generated
   */
  NumericalValue getDeplacement();

  /**
   * Sets the value of the '{@link org.bpy.electronics.mc6809.assembler.assembler.AutoIncDecMode#getDeplacement <em>Deplacement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Deplacement</em>' containment reference.
   * @see #getDeplacement()
   * @generated
   */
  void setDeplacement(NumericalValue value);

  /**
   * Returns the value of the '<em><b>Decrement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decrement</em>' attribute.
   * @see #setDecrement(String)
   * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getAutoIncDecMode_Decrement()
   * @model
   * @generated
   */
  String getDecrement();

  /**
   * Sets the value of the '{@link org.bpy.electronics.mc6809.assembler.assembler.AutoIncDecMode#getDecrement <em>Decrement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decrement</em>' attribute.
   * @see #getDecrement()
   * @generated
   */
  void setDecrement(String value);

  /**
   * Returns the value of the '<em><b>Register</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Register</em>' attribute.
   * @see #setRegister(String)
   * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getAutoIncDecMode_Register()
   * @model
   * @generated
   */
  String getRegister();

  /**
   * Sets the value of the '{@link org.bpy.electronics.mc6809.assembler.assembler.AutoIncDecMode#getRegister <em>Register</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Register</em>' attribute.
   * @see #getRegister()
   * @generated
   */
  void setRegister(String value);

  /**
   * Returns the value of the '<em><b>Increment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Increment</em>' attribute.
   * @see #setIncrement(String)
   * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getAutoIncDecMode_Increment()
   * @model
   * @generated
   */
  String getIncrement();

  /**
   * Sets the value of the '{@link org.bpy.electronics.mc6809.assembler.assembler.AutoIncDecMode#getIncrement <em>Increment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Increment</em>' attribute.
   * @see #getIncrement()
   * @generated
   */
  void setIncrement(String value);

} // AutoIncDecMode
