/**
 * generated by Xtext 2.28.0
 */
package org.bpy.electronics.mc6809.assembler.assembler;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.ExpressionValue#getExpressionValue <em>Expression Value</em>}</li>
 * </ul>
 *
 * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getExpressionValue()
 * @model
 * @generated
 */
public interface ExpressionValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Expression Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression Value</em>' containment reference.
   * @see #setExpressionValue(EObject)
   * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getExpressionValue_ExpressionValue()
   * @model containment="true"
   * @generated
   */
  EObject getExpressionValue();

  /**
   * Sets the value of the '{@link org.bpy.electronics.mc6809.assembler.assembler.ExpressionValue#getExpressionValue <em>Expression Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression Value</em>' containment reference.
   * @see #getExpressionValue()
   * @generated
   */
  void setExpressionValue(EObject value);

} // ExpressionValue
