/**
 * generated by Xtext 2.28.0
 */
package org.bpy.electronics.mc6809.assembler.assembler;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Of Registers</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.bpy.electronics.mc6809.assembler.assembler.ListOfRegisters#getRegisters <em>Registers</em>}</li>
 * </ul>
 *
 * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getListOfRegisters()
 * @model
 * @generated
 */
public interface ListOfRegisters extends EObject
{
  /**
   * Returns the value of the '<em><b>Registers</b></em>' attribute list.
   * The list contents are of type {@link org.bpy.electronics.mc6809.assembler.assembler.Register}.
   * The literals are from the enumeration {@link org.bpy.electronics.mc6809.assembler.assembler.Register}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Registers</em>' attribute list.
   * @see org.bpy.electronics.mc6809.assembler.assembler.Register
   * @see org.bpy.electronics.mc6809.assembler.assembler.AssemblerPackage#getListOfRegisters_Registers()
   * @model unique="false"
   * @generated
   */
  EList<Register> getRegisters();

} // ListOfRegisters
